/** Relationship question bank used for solo play (no sign-in, no database). */
export const SOLO_QUESTIONS: { category: string; prompt: string; options: string[] }[] = [
  { category: "First moves", prompt: "Who made the first move?", options: ["I did", "They did", "It was mutual", "Still arguing about it"] },
  { category: "First moves", prompt: "Where did we first really talk?", options: ["Online", "A friend's place", "School or work", "Somewhere random"] },
  { category: "First moves", prompt: "What did they notice first?", options: ["The smile", "The voice", "The confidence", "The outfit"] },
  { category: "Us", prompt: "Our perfect night in?", options: ["A film and food", "Talking till 3am", "Games", "Doing nothing, together"] },
  { category: "Us", prompt: "Who says sorry first?", options: ["Me", "Them", "Whoever is hungry", "Nobody, we just move on"] },
  { category: "Us", prompt: "Who plans the trips?", options: ["Me", "Them", "Both of us", "Nobody, we improvise"] },
  { category: "Us", prompt: "Our love language?", options: ["Words", "Time together", "Small gifts", "Touch"] },
  { category: "Us", prompt: "Biggest thing we argue about?", options: ["Time", "Money", "Food", "Nothing serious"] },
  { category: "Habits", prompt: "Who takes longer to get ready?", options: ["Me", "Them", "Same", "Depends where we are going"] },
  { category: "Habits", prompt: "Who is the better cook?", options: ["Me", "Them", "Neither", "We order in"] },
  { category: "Habits", prompt: "Who falls asleep first?", options: ["Me", "Them", "Same time", "Whoever had the longer day"] },
  { category: "Habits", prompt: "Who checks their phone more?", options: ["Me", "Them", "Both of us", "Neither, we are present"] },
  { category: "Feelings", prompt: "What makes them feel most loved?", options: ["Being listened to", "Being surprised", "Being held", "Being left to rest"] },
  { category: "Feelings", prompt: "How do they act when stressed?", options: ["Very quiet", "Very talkative", "They clean", "They disappear for a bit"] },
  { category: "Feelings", prompt: "Which compliment lands hardest?", options: ["You are kind", "You are funny", "You are gorgeous", "I am proud of you"] },
  { category: "Feelings", prompt: "Their comfort after a bad day?", options: ["Food", "Sleep", "A long call", "Music"] },
  { category: "Future", prompt: "Where do we end up?", options: ["Somewhere warm", "A big city", "Close to family", "Wherever we can afford"] },
  { category: "Future", prompt: "First big thing we buy together?", options: ["A home", "A car", "A trip", "A pet"] },
  { category: "Future", prompt: "In five years we are?", options: ["Married", "Travelling", "Building something", "Exactly like this"] },
  { category: "Future", prompt: "Who would spoil the kids more?", options: ["Me", "Them", "Both, badly", "Neither of us"] },
];
