/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SoloRouteImport } from './routes/solo'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as GamesRouteImport } from './routes/games'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as SoloIndexRouteImport } from './routes/solo.index'
import { Route as GamesIndexRouteImport } from './routes/games.index'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as SoloGameRouteImport } from './routes/solo.$game'
import { Route as GamesGameRouteImport } from './routes/games.$game'
import { Route as AuthenticatedRoomRouteImport } from './routes/_authenticated/room'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPlayRouteImport } from './routes/_authenticated/play'
import { Route as AuthenticatedPairRouteImport } from './routes/_authenticated/pair'
import { Route as AuthenticatedDeleteAccountRouteImport } from './routes/_authenticated/delete-account'
import { Route as AuthenticatedOnlineRoomIdRouteImport } from './routes/_authenticated/online.$roomId'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SoloRoute = SoloRouteImport.update({
  id: '/solo',
  path: '/solo',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const SoloIndexRoute = SoloIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SoloRoute,
} as any)
const GamesIndexRoute = GamesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GamesRoute,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const SoloGameRoute = SoloGameRouteImport.update({
  id: '/$game',
  path: '/$game',
  getParentRoute: () => SoloRoute,
} as any)
const GamesGameRoute = GamesGameRouteImport.update({
  id: '/$game',
  path: '/$game',
  getParentRoute: () => GamesRoute,
} as any)
const AuthenticatedRoomRoute = AuthenticatedRoomRouteImport.update({
  id: '/room',
  path: '/room',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlayRoute = AuthenticatedPlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPairRoute = AuthenticatedPairRouteImport.update({
  id: '/pair',
  path: '/pair',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDeleteAccountRoute =
  AuthenticatedDeleteAccountRouteImport.update({
    id: '/delete-account',
    path: '/delete-account',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnlineRoomIdRoute =
  AuthenticatedOnlineRoomIdRouteImport.update({
    id: '/online/$roomId',
    path: '/online/$roomId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/games': typeof GamesRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/solo': typeof SoloRouteWithChildren
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/delete-account': typeof AuthenticatedDeleteAccountRoute
  '/pair': typeof AuthenticatedPairRoute
  '/play': typeof AuthenticatedPlayRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/room': typeof AuthenticatedRoomRoute
  '/games/$game': typeof GamesGameRoute
  '/solo/$game': typeof SoloGameRoute
  '/games/': typeof GamesIndexRoute
  '/solo/': typeof SoloIndexRoute
  '/online/$roomId': typeof AuthenticatedOnlineRoomIdRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/delete-account': typeof AuthenticatedDeleteAccountRoute
  '/pair': typeof AuthenticatedPairRoute
  '/play': typeof AuthenticatedPlayRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/room': typeof AuthenticatedRoomRoute
  '/games/$game': typeof GamesGameRoute
  '/solo/$game': typeof SoloGameRoute
  '/': typeof AuthenticatedIndexRoute
  '/games': typeof GamesIndexRoute
  '/solo': typeof SoloIndexRoute
  '/online/$roomId': typeof AuthenticatedOnlineRoomIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/games': typeof GamesRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/solo': typeof SoloRouteWithChildren
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/_authenticated/delete-account': typeof AuthenticatedDeleteAccountRoute
  '/_authenticated/pair': typeof AuthenticatedPairRoute
  '/_authenticated/play': typeof AuthenticatedPlayRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/room': typeof AuthenticatedRoomRoute
  '/games/$game': typeof GamesGameRoute
  '/solo/$game': typeof SoloGameRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/games/': typeof GamesIndexRoute
  '/solo/': typeof SoloIndexRoute
  '/_authenticated/online/$roomId': typeof AuthenticatedOnlineRoomIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/games'
    | '/onboarding'
    | '/privacy'
    | '/solo'
    | '/support'
    | '/terms'
    | '/delete-account'
    | '/pair'
    | '/play'
    | '/profile'
    | '/room'
    | '/games/$game'
    | '/solo/$game'
    | '/games/'
    | '/solo/'
    | '/online/$roomId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/onboarding'
    | '/privacy'
    | '/support'
    | '/terms'
    | '/delete-account'
    | '/pair'
    | '/play'
    | '/profile'
    | '/room'
    | '/games/$game'
    | '/solo/$game'
    | '/'
    | '/games'
    | '/solo'
    | '/online/$roomId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/games'
    | '/onboarding'
    | '/privacy'
    | '/solo'
    | '/support'
    | '/terms'
    | '/_authenticated/delete-account'
    | '/_authenticated/pair'
    | '/_authenticated/play'
    | '/_authenticated/profile'
    | '/_authenticated/room'
    | '/games/$game'
    | '/solo/$game'
    | '/_authenticated/'
    | '/games/'
    | '/solo/'
    | '/_authenticated/online/$roomId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  GamesRoute: typeof GamesRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  PrivacyRoute: typeof PrivacyRoute
  SoloRoute: typeof SoloRouteWithChildren
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solo': {
      id: '/solo'
      path: '/solo'
      fullPath: '/solo'
      preLoaderRoute: typeof SoloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solo/': {
      id: '/solo/'
      path: '/'
      fullPath: '/solo/'
      preLoaderRoute: typeof SoloIndexRouteImport
      parentRoute: typeof SoloRoute
    }
    '/games/': {
      id: '/games/'
      path: '/'
      fullPath: '/games/'
      preLoaderRoute: typeof GamesIndexRouteImport
      parentRoute: typeof GamesRoute
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/solo/$game': {
      id: '/solo/$game'
      path: '/$game'
      fullPath: '/solo/$game'
      preLoaderRoute: typeof SoloGameRouteImport
      parentRoute: typeof SoloRoute
    }
    '/games/$game': {
      id: '/games/$game'
      path: '/$game'
      fullPath: '/games/$game'
      preLoaderRoute: typeof GamesGameRouteImport
      parentRoute: typeof GamesRoute
    }
    '/_authenticated/room': {
      id: '/_authenticated/room'
      path: '/room'
      fullPath: '/room'
      preLoaderRoute: typeof AuthenticatedRoomRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/play': {
      id: '/_authenticated/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof AuthenticatedPlayRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pair': {
      id: '/_authenticated/pair'
      path: '/pair'
      fullPath: '/pair'
      preLoaderRoute: typeof AuthenticatedPairRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/delete-account': {
      id: '/_authenticated/delete-account'
      path: '/delete-account'
      fullPath: '/delete-account'
      preLoaderRoute: typeof AuthenticatedDeleteAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/online/$roomId': {
      id: '/_authenticated/online/$roomId'
      path: '/online/$roomId'
      fullPath: '/online/$roomId'
      preLoaderRoute: typeof AuthenticatedOnlineRoomIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDeleteAccountRoute: typeof AuthenticatedDeleteAccountRoute
  AuthenticatedPairRoute: typeof AuthenticatedPairRoute
  AuthenticatedPlayRoute: typeof AuthenticatedPlayRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedRoomRoute: typeof AuthenticatedRoomRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedOnlineRoomIdRoute: typeof AuthenticatedOnlineRoomIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDeleteAccountRoute: AuthenticatedDeleteAccountRoute,
  AuthenticatedPairRoute: AuthenticatedPairRoute,
  AuthenticatedPlayRoute: AuthenticatedPlayRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedRoomRoute: AuthenticatedRoomRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedOnlineRoomIdRoute: AuthenticatedOnlineRoomIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface GamesRouteChildren {
  GamesGameRoute: typeof GamesGameRoute
  GamesIndexRoute: typeof GamesIndexRoute
}

const GamesRouteChildren: GamesRouteChildren = {
  GamesGameRoute: GamesGameRoute,
  GamesIndexRoute: GamesIndexRoute,
}

const GamesRouteWithChildren = GamesRoute._addFileChildren(GamesRouteChildren)

interface SoloRouteChildren {
  SoloGameRoute: typeof SoloGameRoute
  SoloIndexRoute: typeof SoloIndexRoute
}

const SoloRouteChildren: SoloRouteChildren = {
  SoloGameRoute: SoloGameRoute,
  SoloIndexRoute: SoloIndexRoute,
}

const SoloRouteWithChildren = SoloRoute._addFileChildren(SoloRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  GamesRoute: GamesRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  PrivacyRoute: PrivacyRoute,
  SoloRoute: SoloRouteWithChildren,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
