/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedQuickMatchRouteImport } from './routes/_authenticated/quick-match'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedLeaderboardRouteImport } from './routes/_authenticated/leaderboard'
import { Route as AuthenticatedJoinRoomRouteImport } from './routes/_authenticated/join-room'
import { Route as AuthenticatedGameRouteImport } from './routes/_authenticated/game'
import { Route as AuthenticatedCreateRoomRouteImport } from './routes/_authenticated/create-room'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQuickMatchRoute = AuthenticatedQuickMatchRouteImport.update({
  id: '/quick-match',
  path: '/quick-match',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeaderboardRoute =
  AuthenticatedLeaderboardRouteImport.update({
    id: '/leaderboard',
    path: '/leaderboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedJoinRoomRoute = AuthenticatedJoinRoomRouteImport.update({
  id: '/join-room',
  path: '/join-room',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGameRoute = AuthenticatedGameRouteImport.update({
  id: '/game',
  path: '/game',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCreateRoomRoute = AuthenticatedCreateRoomRouteImport.update({
  id: '/create-room',
  path: '/create-room',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/create-room': typeof AuthenticatedCreateRoomRoute
  '/game': typeof AuthenticatedGameRoute
  '/join-room': typeof AuthenticatedJoinRoomRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/quick-match': typeof AuthenticatedQuickMatchRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/create-room': typeof AuthenticatedCreateRoomRoute
  '/game': typeof AuthenticatedGameRoute
  '/join-room': typeof AuthenticatedJoinRoomRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/quick-match': typeof AuthenticatedQuickMatchRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/_authenticated/create-room': typeof AuthenticatedCreateRoomRoute
  '/_authenticated/game': typeof AuthenticatedGameRoute
  '/_authenticated/join-room': typeof AuthenticatedJoinRoomRoute
  '/_authenticated/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/quick-match': typeof AuthenticatedQuickMatchRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/create-room'
    | '/game'
    | '/join-room'
    | '/leaderboard'
    | '/profile'
    | '/quick-match'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/onboarding'
    | '/create-room'
    | '/game'
    | '/join-room'
    | '/leaderboard'
    | '/profile'
    | '/quick-match'
    | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/onboarding'
    | '/_authenticated/create-room'
    | '/_authenticated/game'
    | '/_authenticated/join-room'
    | '/_authenticated/leaderboard'
    | '/_authenticated/profile'
    | '/_authenticated/quick-match'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quick-match': {
      id: '/_authenticated/quick-match'
      path: '/quick-match'
      fullPath: '/quick-match'
      preLoaderRoute: typeof AuthenticatedQuickMatchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leaderboard': {
      id: '/_authenticated/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AuthenticatedLeaderboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/join-room': {
      id: '/_authenticated/join-room'
      path: '/join-room'
      fullPath: '/join-room'
      preLoaderRoute: typeof AuthenticatedJoinRoomRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/game': {
      id: '/_authenticated/game'
      path: '/game'
      fullPath: '/game'
      preLoaderRoute: typeof AuthenticatedGameRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/create-room': {
      id: '/_authenticated/create-room'
      path: '/create-room'
      fullPath: '/create-room'
      preLoaderRoute: typeof AuthenticatedCreateRoomRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCreateRoomRoute: typeof AuthenticatedCreateRoomRoute
  AuthenticatedGameRoute: typeof AuthenticatedGameRoute
  AuthenticatedJoinRoomRoute: typeof AuthenticatedJoinRoomRoute
  AuthenticatedLeaderboardRoute: typeof AuthenticatedLeaderboardRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedQuickMatchRoute: typeof AuthenticatedQuickMatchRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCreateRoomRoute: AuthenticatedCreateRoomRoute,
  AuthenticatedGameRoute: AuthenticatedGameRoute,
  AuthenticatedJoinRoomRoute: AuthenticatedJoinRoomRoute,
  AuthenticatedLeaderboardRoute: AuthenticatedLeaderboardRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedQuickMatchRoute: AuthenticatedQuickMatchRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
